import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {join,resolve} from 'node:path';
import {DATA_LANGUAGES,DATA_PAGES} from '../assets/js/data-routes.mjs';
import {languageConfig} from '../assets/js/data-i18n.mjs';
import {dataViews,comparisonSentence} from '../assets/js/data-views-i18n.mjs';
import * as VIEWS from '../assets/js/data-view-core.mjs';

const root=resolve(import.meta.dirname,'..'),registry=JSON.parse(readFileSync(join(root,'assets/data/indicators.json'),'utf8')),payloads=registry.indicators.map(item=>JSON.parse(readFileSync(join(root,'assets/data/worldbank',`${item.slug}.json`),'utf8'))),languages=Object.keys(DATA_LANGUAGES);
const two=VIEWS.comparisonSummary(payloads,registry.indicators,['USA','CHN']);
assert.ok(two.length>0&&two.length<8);assert.ok(two.every(row=>registry.indicators.includes(row.item)));
for(const row of two){const text=dataViews('es'),local=languageConfig('es').indicators[row.item.slug]||row.item,formatted=VIEWS.formatComparisonDifference(row.item,{...row.item,...local,presentation:{...row.item.presentation,unitLabel:local.unitLabel||row.item.presentation.unitLabel}},'es-ES',row.difference,text.points);if(row.item.presentation.changeType==='percentage_points')assert.match(formatted,/puntos porcentuales$/);else assert.doesNotMatch(formatted,/puntos porcentuales$/);const sentence=comparisonSentence('es',{first:'A',second:'B',value:formatted,year:row.year,relation:row.relation});assert.doesNotMatch(sentence,/Δ/);assert.match(sentence,/\(\d{4}\)\.$/)}
for(const slug of ['poblacion','esperanza-de-vida','fertilidad','pib-per-capita'])assert.notEqual(registry.indicators.find(item=>item.slug===slug).presentation.changeType,'percentage_points');
for(const slug of ['crecimiento-pib','desempleo','uso-de-internet','energia-renovable'])assert.equal(registry.indicators.find(item=>item.slug===slug).presentation.changeType,'percentage_points');
for(const item of registry.indicators){const text=dataViews('es'),local=languageConfig('es').indicators[item.slug]||item,formatted=VIEWS.formatComparisonDifference(item,{...item,...local,presentation:{...item.presentation,unitLabel:local.unitLabel||item.presentation.unitLabel}},'es-ES',1.25,text.points);if(item.presentation.changeType==='percentage_points')assert.equal(formatted,'1,25 puntos porcentuales');else assert.ok(formatted.length>4,`${item.slug}: unidad ausente`)}
const syntheticItems=[{slug:'x',presentation:{changeType:'percentage_points'}}],sameYear=[{observations:[{country:'AAA',year:2024,value:1},{country:'BBB',year:2024,value:3},{country:'CCC',year:2024,value:2}]}],differentYears=[{observations:[{country:'AAA',year:2024,value:1},{country:'BBB',year:2023,value:3}]}],missing=[{observations:[{country:'AAA',year:2024,value:1}]}];
assert.equal(VIEWS.comparisonSummary(sameYear,syntheticItems,['AAA','BBB']).at(0).relation,'less');assert.equal(VIEWS.comparisonSummary(sameYear,syntheticItems,['BBB','AAA']).at(0).relation,'more');assert.equal(VIEWS.comparisonSummary([{observations:[{country:'AAA',year:2024,value:1},{country:'BBB',year:2024,value:1}]}],syntheticItems,['AAA','BBB']).at(0).relation,'equal');assert.deepEqual(VIEWS.comparisonSummary(sameYear,syntheticItems,['AAA','BBB','CCC']).at(0),{item:syntheticItems[0],year:2024,first:'BBB',second:'AAA',difference:2,relation:'more'});assert.equal(VIEWS.comparisonSummary(differentYears,syntheticItems,['AAA','BBB']).length,0);assert.equal(VIEWS.comparisonSummary(missing,syntheticItems,['AAA','BBB']).length,0);
for(const language of languages){const text=dataViews(language),route=DATA_PAGES.compare[language],html=readFileSync(join(root,...route.split('/').filter(Boolean),'index.html'),'utf8');for(const key of ['intro','help','interpretTitle','interpret','sourcesLink'])assert.ok(text[key],`${language}: ${key}`);assert.ok(html.includes(text.intro.replaceAll('&','&amp;'))||html.includes(text.intro));assert.ok(html.includes(`aria-describedby="compare_search_help"`));assert.ok(html.includes(text.interpretTitle));assert.ok(html.includes(`href="${DATA_PAGES.sources[language]}"`));assert.ok(html.includes('id="compare_js_note"'));assert.doesNotMatch(html,/Δ|�/);for(const relation of ['more','less','equal'])assert.doesNotMatch(comparisonSentence(language,{first:'A',second:'B',value:'1',year:2024,relation}),/Δ/)}
const script=readFileSync(join(root,'assets/js/data-views.js'),'utf8');assert.match(script,/compare_js_note/);assert.match(script,/jsNote\.hidden=true/);for(const token of ['ArrowDown','ArrowUp','aria-activedescendant','aria-selected'])assert.ok(script.includes(token));
const ca=readFileSync(join(root,...DATA_PAGES.compare.ca.split('/').filter(Boolean),'index.html'),'utf8');assert.ok(ca.includes('Estats Units'));assert.ok(ca.includes('Xina'));
console.log('data-compare-copy: 8 unidades, relaciones, años, 3–5 países, 15 idiomas, fallback JS y CA OK');
