import assert from 'node:assert/strict';
import {existsSync,readFileSync} from 'node:fs';
import {join,resolve} from 'node:path';
import {DATA_LANGUAGES,DATA_PAGES} from '../assets/js/data-routes.mjs';
import {changeText,CHANGE_TEXT} from '../assets/js/data-change-i18n.mjs';

const root=resolve(import.meta.dirname,'..'),languages=Object.keys(DATA_LANGUAGES),origin='https://metaphai.com',htmlFor=route=>readFileSync(join(root,...route.split('/').filter(Boolean),'index.html'),'utf8');
assert.equal(languages.length,15);assert.equal(Object.keys(CHANGE_TEXT).length,15);
const topology=JSON.parse(readFileSync(join(root,'assets/maps/world-50m.topo.json'),'utf8')),geometries=topology.objects.countries.geometries,mapped=new Set(geometries.map(item=>item.properties.iso3).filter(Boolean));assert.equal(geometries.length,241);assert.equal(mapped.size,215);assert.equal(mapped.has('GIB'),false);assert.equal(mapped.has('TUV'),false);
const defaults=[];
for(const language of languages){const route=DATA_PAGES.changes[language],text=changeText(language),file=join(root,...route.split('/').filter(Boolean),'index.html');assert.ok(existsSync(file),`${language}: página ausente`);const html=htmlFor(route),head=html.match(/<head>([\s\S]*?)<\/head>/)?.[1]||'';assert.match(html,new RegExp(`<html lang="${language}"${language==='ar'?' dir="rtl"':''}>`));assert.ok(head.includes(`<link rel="canonical" href="${origin}${route}">`));assert.ok(head.includes(`<meta property="og:url" content="${origin}${route}">`));for(const alternate of languages)assert.ok(head.includes(`hreflang="${alternate}" href="${origin}${DATA_PAGES.changes[alternate]}"`));assert.ok(head.includes(`hreflang="x-default" href="${origin}${DATA_PAGES.changes.es}"`));for(const token of [text.title,text.intro,text.category,text.indicator,text.from,text.to,text.largestIncreases,text.largestDecreases,text.allResults,text.methodology,'data.css?v=20260914-10','data-changes.js?v=20260914-10','data-page-key="changes"','id="change_world_map"','id="change_top_increase"','id="change_top_decrease"','id="change_all_results"'])assert.ok(html.includes(token),`${language}: falta ${token}`);assert.ok(html.includes(`href="${route}" aria-current="page"`));assert.ok(htmlFor(DATA_PAGES.home[language]).includes(`href="${route}"`),`${language}: card landing ausente`);assert.equal(html.includes('�'),false);assert.doesNotMatch(html,/[?&](?:indicator|from|to)=/);defaults.push(html.match(/id="change_coverage_value">(\d+)</)?.[1])}
assert.equal(new Set(defaults).size,1);assert.equal(defaults[0],'217');
assert.equal(changeText('es').intro,'Compara dos años y descubre en qué países ha aumentado o disminuido más cada indicador.');for(const language of languages){assert.ok(changeText(language).intro.length>10,`${language}: introducción incompleta`);assert.notEqual(changeText(language).intro,changeText(language).card,`${language}: Cambios no debe reutilizar el texto de su tarjeta`)}
const sitemap=readFileSync(join(root,'sitemap.xml'),'utf8'),locs=[...sitemap.matchAll(/<loc>([^<]+)<\/loc>/g)].map(match=>match[1]);assert.equal(locs.length,3801);assert.equal(new Set(locs).size,locs.length);for(const language of languages)assert.ok(locs.includes(`${origin}${DATA_PAGES.changes[language]}`));assert.doesNotMatch(sitemap,/(?:indicator|from|to)=/);
const runtime=readFileSync(join(root,'assets/js/data-changes.js'),'utf8');for(const token of ['CHANGE.comparableChanges','CHANGE.robustExtent','d3.geoEqualEarth','world-50m.topo.json','history[push?\'pushState\':\'replaceState\']','popstate','CORE.searchCountries','bindPointerOptionSelection(list,choose)','navigateToCountryProfile(language,code,state.validCodes)','VIEWS.validCountries','state.localized',"classList.toggle('is-selected'", ".on('pointerenter'", ".on('focus'", ".on('click'", "event.key==='Enter'", "event.key==='Escape'"])assert.ok(runtime.includes(token),`contrato runtime ausente: ${token}`);assert.equal(runtime.includes('api.worldbank.org'),false);assert.equal((runtime.match(/worldbank\/\$\{item\.slug\}/g)||[]).length,1);assert.doesNotMatch(runtime,/touchend/);
const css=readFileSync(join(root,'assets/css/data.css'),'utf8');assert.match(css,/\.change-controls\{[^}]*grid-template-columns/);assert.match(css,/@media\(max-width:560px\)[\s\S]*?\.change-controls\{grid-template-columns:1fr\}/);assert.match(css,/\.change-rankings\{[^}]*grid-template-columns:1fr 1fr/);
console.log('data-changes-integration: 15 páginas, SEO/i18n/RTL, contenido prerender, landing/nav, sitemap 3801, carga bajo demanda y mapa compartido OK');
