import assert from 'node:assert/strict';
import {existsSync,readFileSync} from 'node:fs';
import {createRequire} from 'node:module';
import {join,resolve} from 'node:path';
import {DATA_LANGUAGES,DATA_PAGES,countryRoute} from '../assets/js/data-routes.mjs';
import {languageConfig} from '../assets/js/data-i18n.mjs';
import {mapText} from '../assets/js/data-map-i18n.mjs';
import * as MAP from '../assets/js/data-map-core.mjs';

const root=resolve(import.meta.dirname,'..'),json=path=>JSON.parse(readFileSync(join(root,path),'utf8')),registry=json('assets/data/indicators.json'),countries=json('assets/data/worldbank/countries.json').countries,valid=countries.filter(country=>!country.is_aggregate),validCodes=new Set(valid.map(country=>country.id)),topology=json('assets/maps/world-50m.topo.json'),geometries=topology.objects.countries.geometries,languages=Object.keys(DATA_LANGUAGES),origin='https://metaphai.com';
const require=createRequire(import.meta.url),d3=require('../assets/vendor/d3.v7.9.0.min.js'),topojson=require('../assets/vendor/topojson-client.v3.1.0.min.js'),features=topojson.feature(topology,topology.objects.countries),projection=d3.geoEqualEarth().fitExtent([[8,8],[952,492]],features),paths=features.features.map(d3.geoPath(projection));
assert.equal(geometries.length,241);assert.equal(new Set(geometries.map(item=>item.id)).size,241,'IDs cartográficos duplicados');
assert.equal(paths.length,241);assert.ok(paths.every(path=>path&&!path.includes('NaN')),'la geometría debe producir 241 trazados SVG válidos');
assert.equal(MAP.resolvedMapYear({observations:[{country:'ESP',year:2020,value:1}]},countries,2099),2020);
const mapped=new Set(geometries.map(item=>item.properties.iso3).filter(Boolean));for(const code of mapped)assert.ok(validCodes.has(code),`geometría asociada a agregado/desconocido: ${code}`);
assert.equal(mapped.size,215);assert.deepEqual(valid.map(country=>country.id).filter(code=>!mapped.has(code)).sort(),['GIB','TUV']);
assert.equal(geometries.filter(item=>item.properties.iso3==='XKX').length,1);assert.equal(geometries.filter(item=>item.properties.iso3==='CHI').length,2);assert.equal(geometries.filter(item=>item.properties.iso3==='AUS').length,2);assert.deepEqual([...Map.groupBy(geometries.filter(item=>item.properties.iso3),item=>item.properties.iso3)].filter(([,items])=>items.length>1).map(([code])=>code).sort(),['AUS','CHI']);assert.ok(geometries.every(item=>item.properties.map_id===item.id));
assert.ok(existsSync(join(root,'assets/maps/world-atlas.LICENSE.txt')));assert.ok(readFileSync(join(root,'assets/maps/README.md'),'utf8').includes('Natural Earth'));
const population=json('assets/data/worldbank/poblacion.json'),years=MAP.availableYears(population,countries),defaultYear=MAP.defaultMapYear(population,countries,registry.common_year_coverage);assert.equal(defaultYear,2025);assert.ok(years.includes(1960)&&years.includes(2025));assert.equal(MAP.normalizedMapState('?indicator=poblacion&year=2000',registry).year,2000);assert.equal(MAP.normalizedMapState('?indicator=bad&year=x',registry).item.slug,registry.indicators[0].slug);assert.deepEqual(MAP.quantileBreaks([1,2,3,4,5],5),[1.8,2.6,3.4,4.2]);assert.equal(MAP.colorIndex(null,[1,2]),-1);const ranked=MAP.rankingForYear({observations:[{country:'ESP',year:2020,value:2},{country:'FRA',year:2020,value:2},{country:'WLD',year:2020,value:9}]},countries,{ranking:'descending'},2020);assert.deepEqual(ranked.map(row=>[row.country,row.position]),[['ESP',1],['FRA',1]]);
const sitemap=readFileSync(join(root,'sitemap.xml'),'utf8');assert.equal((sitemap.match(/<loc>[^<]+(?:\/mapa|\/map|\/carte|\/karte|\/mappa)\/<\/loc>/g)||[]).length,15);assert.doesNotMatch(sitemap,/[?&](?:indicator|year)=/);
for(const language of languages){const route=DATA_PAGES.map[language],file=join(root,...route.split('/').filter(Boolean),'index.html'),html=readFileSync(file,'utf8'),text=mapText(language),landing=readFileSync(join(root,...DATA_PAGES.home[language].split('/').filter(Boolean),'index.html'),'utf8');assert.match(html,new RegExp(`<html lang="${language}"${language==='ar'?' dir="rtl"':''}>`));assert.ok(html.includes(`<link rel="canonical" href="${origin}${route}">`));for(const alt of languages)assert.ok(html.includes(`hreflang="${alt}" href="${origin}${DATA_PAGES.map[alt]}"`));assert.ok(html.includes(`hreflang="x-default" href="${origin}${DATA_PAGES.map.es}"`));for(const id of ['map_app','map_indicator','map_year','map_country','map_legend','world_map','map_panel','map_js_note'])assert.ok(html.includes(`id="${id}"`),`${language}: falta ${id}`);assert.equal((html.match(/<optgroup/g)||[]).length,6);assert.equal((html.match(/<option value="/g)||[]).length,22);for(const key of ['title','intro','year','legend','jsRequired','methodology'])assert.ok(html.includes(text[key]));assert.ok(landing.includes(`href="${route}"`));assert.ok(html.includes('d3.v7.9.0.min.js')&&html.includes('topojson-client.v3.1.0.min.js')&&html.includes('data-map.js?v=20260914-4'));assert.ok(html.includes(`data-page-key="map"`));assert.equal(html.includes('�'),false);assert.ok(countryRoute(language,'GIB'))}
const runtime=readFileSync(join(root,'assets/js/data-map.js'),'utf8');assert.equal(runtime.includes('api.worldbank.org'),false);assert.equal(runtime.includes('source_name'),false);assert.match(runtime,/world-50m\.topo\.json/);assert.match(runtime,/worldbank\/\$\{state\.item\.slug\}\.json/);assert.equal((runtime.match(/worldbank\//g)||[]).length,2);for(const token of [".attr('tabindex'",".on('focus'",".on('keydown',mapKeydown)","event.key==='ArrowRight'","event.key==='Enter'","history[push?'pushState':'replaceState']",'popstate'])assert.ok(runtime.includes(token),`contrato de interacción ausente: ${token}`);
console.log('data-map: 241 geometrías únicas, cobertura 215/217, 22 indicadores, 15 páginas, SEO/i18n/estado/ranking OK');
