import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import * as CHANGE from '../assets/js/data-change-core.mjs';

const json=path=>JSON.parse(readFileSync(new URL(`../${path}`,import.meta.url),'utf8')),registry=json('assets/data/indicators.json'),countries=json('assets/data/worldbank/countries.json').countries,item=slug=>registry.indicators.find(entry=>entry.slug===slug);
assert.equal(registry.indicators.length,22);assert.equal(registry.categories.length,6);
assert.equal(CHANGE.changeType(item('esperanza-de-vida')),'natural');assert.equal(CHANGE.changeType(item('poblacion')),'percent');assert.equal(CHANGE.changeType(item('uso-de-internet')),'percentage_points');
assert.ok(Math.abs(CHANGE.calculateChange(70,76.4,'natural')-6.4)<1e-9);assert.equal(CHANGE.calculateChange(10,12,'percent'),20);assert.equal(CHANGE.calculateChange(20,25,'percentage_points'),5);assert.equal(CHANGE.calculateChange(0,5,'percent'),null);assert.equal(CHANGE.calculateChange(-2,-1,'percent'),50);assert.equal(CHANGE.calculateChange(null,1,'natural'),null);
const syntheticCountries=[{id:'AAA',iso2:'AA',is_aggregate:false},{id:'BBB',iso2:'BB',is_aggregate:false},{id:'CCC',iso2:'CC',is_aggregate:false},{id:'DDD',iso2:'DD',is_aggregate:false},{id:'WLD',iso2:'1W',is_aggregate:true}],synthetic={observations:[{country:'AAA',year:2000,value:10},{country:'AAA',year:2020,value:15},{country:'BBB',year:2000,value:10},{country:'BBB',year:2020,value:15},{country:'CCC',year:2000,value:5},{country:'CCC',year:2020,value:4},{country:'DDD',year:2000,value:5},{country:'WLD',year:2000,value:1},{country:'WLD',year:2020,value:2}]},rows=CHANGE.comparableChanges(synthetic,syntheticCountries,item('poblacion'),2000,2020),ranked=CHANGE.rankedChanges(rows);
assert.equal(rows.length,3);assert.deepEqual(ranked.map(row=>row.position),[1,1,3]);assert.deepEqual(CHANGE.changeSummary([{change:-2},{change:0},{change:4}]),{coverage:3,median:0,increase:1,decrease:1,unchanged:1});
assert.equal(CHANGE.divergentColor(-1,10),CHANGE.DECREASE_COLORS[0]);assert.equal(CHANGE.divergentColor(0,10),CHANGE.ZERO_COLOR);assert.equal(CHANGE.divergentColor(1,10),CHANGE.INCREASE_COLORS[0]);assert.deepEqual(CHANGE.legendValues(10),[-10,-5,0,5,10]);
const life=json('assets/data/worldbank/esperanza-de-vida.json'),period=CHANGE.defaultPeriod(life,countries,item('esperanza-de-vida'),registry.common_year_coverage),actual=CHANGE.comparableChanges(life,countries,item('esperanza-de-vida'),period.from,period.to);assert.ok(period.from<period.to);assert.ok([10,20].includes(period.to-period.from));assert.ok(actual.length>100);assert.deepEqual(CHANGE.resolvedPeriod(life,countries,item('esperanza-de-vida'),period.to,period.from),period);assert.deepEqual(CHANGE.resolvedPeriod(life,countries,item('esperanza-de-vida'),'x','y'),period);
assert.deepEqual(CHANGE.resolvedPeriod(life,countries,item('esperanza-de-vida'),2000,2024),{from:2000,to:2024});
for(const indicator of registry.indicators){const payload=json(`assets/data/worldbank/${indicator.slug}.json`),selection=CHANGE.defaultPeriod(payload,countries,indicator,registry.common_year_coverage),changes=CHANGE.comparableChanges(payload,countries,indicator,selection.from,selection.to);assert.ok(selection.from<selection.to,`${indicator.slug}: periodo`);assert.ok(changes.length>0,`${indicator.slug}: cobertura`);assert.ok(changes.every(row=>Number.isFinite(row.change)&&row.fromYear===selection.from&&row.toYear===selection.to),`${indicator.slug}: cambio no finito`)}
assert.equal(CHANGE.normalizedIndicator('?indicator=uso-de-internet',registry).slug,'uso-de-internet');assert.equal(CHANGE.normalizedIndicator('?indicator=inexistente',registry).slug,'esperanza-de-vida');
console.log(`data-changes-core: 22 indicadores, 6 categorías, natural/porcentaje/pp, nulos/cero/negativos, ranking/ties, mediana y periodo ${period.from}–${period.to} (${actual.length} comparables) OK`);
