import assert from 'node:assert/strict';
import { createReadStream, existsSync, readFileSync, statSync } from 'node:fs';
import { createServer } from 'node:http';
import { join, resolve } from 'node:path';
import { DATA_LANGUAGES, DATA_PAGES, countryRoute, countryRoutes } from '../assets/js/data-routes.mjs';
import * as CORE from '../assets/js/data-core.mjs';
import * as VIEWS from '../assets/js/data-view-core.mjs';
import { dataViews } from '../assets/js/data-views-i18n.mjs';

const root=resolve(import.meta.dirname,'..'),origin='https://metaphai.com',languages=Object.keys(DATA_LANGUAGES),countriesPayload=JSON.parse(readFileSync(join(root,'assets/data/worldbank/countries.json'),'utf8')),countries=VIEWS.validCountries(countriesPayload.countries),registry=JSON.parse(readFileSync(join(root,'assets/data/indicators.json'),'utf8'));
const fileFor=route=>join(root,...route.split('/').filter(Boolean),'index.html');
const assertLinks=(html,route)=>{for(const match of html.matchAll(/(?:href|src)="([^"#?]+)(?:\?[^"#]*)?"/g)){const target=match[1];if(!target.startsWith('/')||target.startsWith('//'))continue;const file=target.endsWith('/')?fileFor(target):join(root,target.slice(1));assert.ok(existsSync(file),`${route}: enlace roto ${target}`)}};
assert.equal(countries.length,217);assert.equal(countriesPayload.countries.length-countries.length,78);assert.equal(new Set(countries.map(VIEWS.countrySlug)).size,217);assert.ok(countries.every(country=>/^[A-Z]{3}$/.test(country.id)&&/^[A-Z]{2}$/.test(country.iso2)&&!country.is_aggregate));
for(const language of languages){const strings=dataViews(language);for(const key of ['explore','countries','compare','rankings','countriesTitle','compareTitle','rankingsTitle','sourceText'])assert.ok(strings[key],`${language}: ${key} ausente`)}
assert.deepEqual(VIEWS.normalizeCountrySelection('ESP,DEU,ESP,XXX,WLD',countries),['ESP','DEU']);assert.deepEqual(VIEWS.normalizeCountrySelection('USA,CHN,IND,JPN,BRA,ESP',countries),['USA','CHN','IND','JPN','BRA']);assert.deepEqual(VIEWS.normalizeCountrySelection('',countries),[]);
assert.deepEqual(CORE.assignRankingPositions([{value:9},{value:8},{value:8},{value:7}]).map(row=>row.position),[1,2,2,4]);

const routeGroups=[DATA_PAGES.countries,DATA_PAGES.compare,DATA_PAGES.rankings,...countries.map(country=>countryRoutes(country.id))],routes=routeGroups.flatMap(group=>languages.map(language=>group[language]));
assert.equal(routes.length,3300);assert.equal(new Set(routes).size,3300);
for(const country of countries)for(const language of languages){const route=countryRoute(language,country.id),file=fileFor(route);assert.ok(existsSync(file),`${route}: falta`);const html=readFileSync(file,'utf8'),name=VIEWS.localizedCountries([country],DATA_LANGUAGES[language].locale)[0].name;assert.match(html,new RegExp(`<html lang="${language}"${language==='ar'?' dir="rtl"':''}>`));assert.ok(html.includes(`<link rel="canonical" href="${origin}${route}">`));assert.ok(html.includes(`data-page-key="country:${country.id}"`));assert.ok(html.includes(`<h1>${name.replaceAll('&','&amp;')}</h1>`)||html.includes(`<h1>${name}</h1>`));assert.ok(html.includes('indicator-category-row'),`${route}: sin indicadores agrupados`);assert.doesNotMatch(html,/data-country-view="(?:WLD|HIC|EMU)"/);assert.match(html,/"@type":"BreadcrumbList"/);for(const alt of languages)assert.ok(html.includes(`hreflang="${alt}" href="${origin}${countryRoute(alt,country.id)}"`),`${route}: hreflang ${alt}`);assert.ok(html.includes(`hreflang="x-default" href="${origin}${countryRoute('es',country.id)}"`));assert.equal(html.includes('�'),false);assertLinks(html,route)}

for(const language of languages)for(const [key,page] of [['countries',DATA_PAGES.countries],['compare',DATA_PAGES.compare],['rankings',DATA_PAGES.rankings]]){const route=page[language],html=readFileSync(fileFor(route),'utf8');assert.ok(html.includes(`<link rel="canonical" href="${origin}${route}">`));assert.ok(html.includes(`data-page-key="${key}"`));assert.match(html,/data-views\.js\?v=20260914-10/);if(key==='countries')assert.equal((html.match(/data-country-code=/g)||[]).length,217);if(key==='compare')for(const id of ['compare_search','comparison_table','compare_chart'])assert.ok(html.includes(`id="${id}"`));if(key==='rankings')for(const id of ['ranking_indicator','ranking_year','rankings_body'])assert.ok(html.includes(`id="${id}"`));assertLinks(html,route)}

for(const item of registry.indicators){const payload=JSON.parse(readFileSync(join(root,`assets/data/worldbank/${item.slug}.json`),'utf8')),years=VIEWS.offeredRankingYears(payload,countries,registry.common_year_coverage),common=CORE.commonYear(VIEWS.indicatorRows(payload,countries),registry.common_year_coverage);assert.ok(years.some(entry=>entry.year===common));assert.ok(years.every(entry=>entry.count>=entry.minimum));const ranked=VIEWS.rankingFor(payload,countries,item,common);assert.ok(ranked.length>=years[0].minimum);assert.ok(ranked.every(row=>countries.some(country=>country.id===row.country)))}

const sitemap=readFileSync(join(root,'sitemap.xml'),'utf8'),locs=[...sitemap.matchAll(/<loc>([^<]+)<\/loc>/g)].map(match=>match[1]);assert.equal(locs.length,9952);assert.equal(new Set(locs).size,9952);for(const route of routes)assert.ok(locs.includes(origin+route),`sitemap: falta ${route}`);assert.ok(Buffer.byteLength(sitemap)<50_000_000);

const server=createServer((request,response)=>{const file=fileFor(new URL(request.url,'http://local').pathname);if(!existsSync(file)||!statSync(file).isFile()){response.writeHead(404);response.end();return}response.writeHead(200,{'content-type':'text/html; charset=utf-8'});createReadStream(file).pipe(response)});await new Promise(done=>server.listen(0,'127.0.0.1',done));let http=0;try{const port=server.address().port;for(const route of routes){const response=await fetch(`http://127.0.0.1:${port}${route}`);assert.equal(response.status,200,route);http++}}finally{await new Promise(done=>server.close(done))}
assert.equal(http,3300);
const viewsSource=readFileSync(join(root,'assets/js/data-views.js'),'utf8');for(const token of ['ArrowDown','ArrowUp','aria-activedescendant','splitOnGaps','axisFont=mobile?14:10','tabindex="0"'])assert.ok(viewsSource.includes(token),`Contrato interactivo ausente: ${token}`);
for(const code of ['ESP','USA','CHN','IND','JPN','BRA','ERI','TUV'])assert.ok(countries.some(country=>country.id===code),`${code}: caso representativo ausente`);
console.log(`data-country-views: ${countries.length} entidades, 3300/3300 páginas HTTP, SEO/hreflang, rankings y sitemap ${locs.length} OK`);
