import assert from 'node:assert/strict';
import {existsSync,readFileSync} from 'node:fs';
import {join,relative,resolve} from 'node:path';
import {DATA_LANGUAGES,DATA_PAGES,INSTITUTIONAL_PAGES} from '../assets/js/data-routes.mjs';

const root=resolve(import.meta.dirname,'..'),version='20260914-10',interactiveVersion='20260914-10',origin='https://metaphai.com',languages=Object.keys(DATA_LANGUAGES),entries=Object.entries(DATA_PAGES);
const htmlByRoute=route=>readFileSync(join(root,...route.split('/').filter(Boolean),'index.html'),'utf8'),allRoutes=entries.flatMap(([,page])=>languages.map(language=>page[language]));
assert.equal(entries.length,30);assert.equal(languages.length,15);assert.equal(new Set(allRoutes).size,450);
const prefixes={es:'/datos-globales/',en:'/en/global-data/',fr:'/fr/donnees-mondiales/',de:'/de/weltdaten/',it:'/it/dati-globali/',pt:'/pt/dados-globais/',ru:'/ru/global-data/','zh-CN':'/zh-cn/global-data/',hi:'/hi/global-data/',ja:'/ja/global-data/',ko:'/ko/global-data/',ca:'/ca/global-data/',ar:'/ar/global-data/',id:'/id/global-data/',bn:'/bn/global-data/'};
for(const [key,page] of entries)for(const language of languages){const route=page[language],html=htmlByRoute(route),file=join(root,...route.split('/').filter(Boolean),'index.html'),head=html.match(/<head>([\s\S]*?)<\/head>/)?.[1]||'';const ids=[...html.matchAll(/\sid=["']([^"']+)["']/g)].map(match=>match[1]);assert.equal(new Set(ids).size,ids.length,`ID duplicado en ${relative(root,file)}`);assert.match(html,new RegExp(`<html lang="${language}"`));assert.ok(head.includes(`<link rel="canonical" href="${origin}${route}">`));assert.ok(head.includes(`<meta property="og:url" content="${origin}${route}">`));assert.match(head,/<title>[^<]{8,}<\/title>/);assert.match(head,/<meta name="description" content="[^"]{10,}">/);for(const hreflang of languages)assert.ok(head.includes(`<link rel="alternate" hreflang="${hreflang}" href="${origin}${page[hreflang]}">`),`${route}: hreflang ${hreflang}`);assert.ok(head.includes(`<link rel="alternate" hreflang="x-default" href="${origin}${page.es}">`));assert.ok(html.includes(`data-page-key="${key}"`));for(const target of languages)assert.ok(html.includes(`data-language="${target}" href="${page[target]}"`),`${route}: selector ${target}`);assert.match(html,new RegExp(`data-language="${language}"[^>]+aria-current="true"`));assert.match(html,new RegExp(`data\\.css\\?v=${version}`));assert.match(html,new RegExp(`data-language\\.js\\?v=${version}`));assert.doesNotMatch(html,/metaphai\.com\/datos\//);assert.doesNotMatch(html,/href=["']\/datos\//);const withoutSwitcher=html.replace(/<details class="language-switcher"[\s\S]*?<\/details>/,'');for(const other of languages.filter(code=>code!==language))assert.equal(withoutSwitcher.includes(`href="${prefixes[other]}`),false,`Enlace ${other} accidental en ${route}`);for(const block of html.matchAll(/<script\s+type=["']application\/ld\+json["']>([\s\S]*?)<\/script>/g))assert.doesNotThrow(()=>JSON.parse(block[1]),`JSON-LD inválido en ${relative(root,file)}`);for(const link of html.matchAll(/(?:href|src)=["']([^"'#?]+)(?:\?[^"']*)?["']/g)){const target=link[1];if(!target.startsWith('/')||target.startsWith('//'))continue;const local=target.endsWith('/')?join(root,target.slice(1),'index.html'):join(root,target.slice(1));assert.equal(existsSync(local),true,`Ruta inexistente: ${target} en ${relative(root,file)}`)}}
for(const [key,page] of entries)for(const language of languages){const html=htmlByRoute(page[language]);assert.ok(html.includes('data.css?v=20260914-10'),`${key}/${language}: versión CSS inesperada`);assert.ok(html.includes('data-language.js?v=20260914-10'),`${key}/${language}: versión de idioma inesperada`);assert.equal(html.includes('compare-hero'),false,`${key}/${language}: excepción antigua de héroe`)}
for(const key of ['explorer','map','countries','compare','rankings','changes'])for(const language of languages)assert.ok(htmlByRoute(DATA_PAGES[key][language]).includes('class="data-hero'),`${key}/${language}: héroe compartido ausente`);
const interactive=allRoutes.filter(route=>/data-explorer\.js/.test(htmlByRoute(route)));assert.equal(interactive.length,345);for(const route of interactive){const html=htmlByRoute(route);assert.match(html,new RegExp(`data-explorer\\.js\\?v=${interactiveVersion}`));for(const id of ['data_app','year_select','country_search','ranking_body','insights','compare_list','chart','chart_legend','chart_table_body','download_csv','source_box'])assert.match(html,new RegExp(`id=["']${id}["']`),`${id} falta en ${route}`)}
for(const [,page] of entries)for(const language of languages){const html=htmlByRoute(page[language]);for(const target of [DATA_PAGES.sources[language],INSTITUTIONAL_PAGES.privacy[language],INSTITUTIONAL_PAGES.contact[language],INSTITUTIONAL_PAGES.about[language]])assert.ok(html.includes(`<a href="${target}">`),`${page[language]}: footer incorrecto (${target})`)}
for(const language of ['fr','de','it','pt','ru','zh-CN','hi','ja','ko']){const source=htmlByRoute(DATA_PAGES.sources[language]);for(const token of ['World Development Indicators','CC BY 4.0','CSV'])assert.ok(source.includes(token),`${language}: metodología incompleta (${token})`);assert.match(source,/70\s*%/,`${language}: umbral del año común ausente`)}
const explorer=readFileSync(join(root,'assets/js/data-explorer.js'),'utf8'),core=readFileSync(join(root,'assets/js/data-core.mjs'),'utf8'),css=readFileSync(join(root,'assets/css/data.css'),'utf8');for(const token of ["e.key==='ArrowDown'","e.key==='ArrowUp'","e.key==='Enter'","e.key==='Escape'",'aria-activedescendant','aria-expanded','role="combobox"','role="listbox"','onpointerdown','onpointermove','renderChart()','aria-pressed','aria-sort'])assert.ok(explorer.includes(token),`Contrato UI ausente: ${token}`);assert.ok(core.includes('Intl.NumberFormat'));assert.equal(explorer.includes('.toFixed('),false);assert.match(css,/@media\(max-width:600px\)/);assert.match(css,/@media\(max-width:420px\)/);assert.match(css,/touch-action:pan-y/);assert.match(css,/\.language-menu\{[^}]*position:absolute/);assert.match(css,/\.language-menu a\{[^}]*min-height:40px/);assert.match(explorer,/axisFont=mobile\?14:10/);assert.match(explorer,/measureAxisWidth\(tickLabels,axisFont,chart\)\+12/);assert.match(explorer,/getComputedTextLength/);assert.match(explorer,/Intl\.DisplayNames/);assert.match(explorer,/languageConfig\(state\.language\)/);assert.doesNotMatch(explorer,/languageConfig\('es'\)/);
const registry=JSON.parse(readFileSync(join(root,'assets/data/indicators.json'),'utf8'));assert.equal(registry.indicators.length,22);for(const item of registry.indicators)assert.doesNotThrow(()=>JSON.parse(readFileSync(join(root,'assets/data/worldbank',`${item.slug}.json`),'utf8')));const legacyRoutes=['','explorador','fuentes',...registry.indicators.slice(0,8).map(item=>item.slug)];assert.equal(legacyRoutes.length,11);for(const route of legacyRoutes){const legacy=readFileSync(join(root,'datos',route,'index.html'),'utf8'),target=`/datos-globales/${route?`${route}/`:''}`;assert.match(legacy,/<meta name="robots" content="noindex,follow">/);assert.ok(legacy.includes(`<link rel="canonical" href="${origin}${target}">`))}
const sitemap=readFileSync(join(root,'sitemap.xml'),'utf8'),locs=[...sitemap.matchAll(/<loc>([^<]+)<\/loc>/g)].map(match=>match[1]),dataLocs=allRoutes.map(route=>origin+route);assert.doesNotMatch(sitemap,/metaphai\.com\/datos\//);assert.equal(dataLocs.filter(url=>locs.includes(url)).length,450);assert.equal(new Set(locs).size,locs.length);for(const [key,page] of entries)for(const language of languages){const entry=sitemap.match(new RegExp(`<url><loc>${origin.replaceAll('.','\\.')}${page[language]}<\\/loc>([\\s\\S]*?)<\\/url>`))?.[1]||'';for(const alt of languages)assert.ok(entry.includes(`hreflang="${alt}" href="${origin}${page[alt]}"`),`${key}/${language}: sitemap ${alt}`)}
for(const key of ['contact','about'])for(const language of languages)assert.ok(locs.includes(origin+INSTITUTIONAL_PAGES[key][language]),`Sitemap sin ${key}/${language}`);for(const language of languages)assert.equal(locs.includes(origin+INSTITUTIONAL_PAGES.privacy[language]),false,`Privacidad noindex presente en sitemap: ${language}`);
assert.match(css,/\.data-hero\{[^}]*max-width:960px/);assert.match(css,/\.data-hero p\{[^}]*max-width:880px/);assert.doesNotMatch(css,/\.compare-hero/);assert.doesNotMatch(css,/\.data-hero[^}]*text-align:center/);
assert.doesNotMatch(css,/\.data-hero\{[^}]*max-width:800px/);assert.doesNotMatch(css,/\.data-hero p\{[^}]*max-width:720px/);assert.doesNotMatch(css,/\.data-hero[^}]*!important/);
console.log(`data-ui-static: 450 páginas base, ${interactive.length} exploradores/indicadores, 15 idiomas, 30 grupos SEO/idioma y 22 indicadores OK`);
