import assert from 'node:assert/strict';
import { existsSync, readFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { DATA_LANGUAGES, INSTITUTIONAL_PAGES } from '../assets/js/data-routes.mjs';
import { GAME_PAGES } from '../assets/js/games/game-routes.mjs';
import { activeGames } from '../assets/js/games/game-registry.mjs';
import { GAMES_I18N } from '../assets/js/games/games-i18n.mjs';
import { appendBidiText, bidiSegments } from '../assets/js/games/game-ui.mjs';
import { ABOUT_DESCRIPTION } from '../scripts/prerender-games.mjs';
const root=resolve(import.meta.dirname,'..'),origin='https://metaphai.com',fileFor=route=>join(root,...route.split('/').filter(Boolean),'index.html'),institutionalFileFor=route=>route.endsWith('/')?fileFor(route):join(root,...route.split('/').filter(Boolean)),languages=Object.keys(DATA_LANGUAGES),required=['games','gamesTitle','gamesIntro','gameTitle','tagline','cardMeta','play','question','score','correctAnswers','hint','next','finish','correct','incorrect','privacy','unavailable','share','gameStatsTitle','highest','lowest','increase','decrease'];
for(const language of languages){const text=GAMES_I18N[language];for(const key of required)assert.ok(typeof text[key]==='function'||String(text[key]||'').trim(),`${language}:${key}`);for(const [pageKey,routes] of Object.entries(GAME_PAGES)){const route=routes[language],file=fileFor(route);assert.ok(existsSync(file),route);const html=readFileSync(file,'utf8'),head=html.match(/<head>([\s\S]*?)<\/head>/)?.[1]||'';assert.match(html,new RegExp(`<html lang="${language}"${language==='ar'?' dir="rtl"':''}>`));assert.ok(head.includes(`<link rel="canonical" href="${origin}${route}">`));assert.ok(head.includes(`<meta property="og:url" content="${origin}${route}">`));assert.ok(head.includes('summary_large_image'));assert.ok(html.includes(`data-language="${language}" href="${route}"`));for(const alt of languages)assert.ok(head.includes(`hreflang="${alt}" href="${origin}${routes[alt]}"`));assert.ok(head.includes(`hreflang="x-default" href="${origin}${routes.es}"`));assert.ok(html.includes('games.css?v=20260916-3'));assert.equal(html.includes('�'),false);const ids=[...html.matchAll(/\sid="([^"]+)"/g)].map(match=>match[1]);assert.equal(new Set(ids).size,ids.length);for(const block of html.matchAll(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/g))assert.doesNotThrow(()=>JSON.parse(block[1]));if(pageKey==='home'){assert.ok(html.includes('<h1>'+text.games+'</h1>'));assert.equal((html.match(/data-game-id=/g)||[]).length,activeGames().length);assert.ok(html.includes('data-game-id="worldDataQuiz"'));assert.equal(html.includes('data-games-landing'),false);assert.equal(html.includes('data-game-stats'),false);assert.equal(html.includes(text.how),false);assert.equal(html.includes(text.winRule),false);for(const label of [text.played,text.wins,text.winRate,text.currentStreak,text.bestStreak,text.perfect,text.average,text.questionsAnswered,text.totalCorrect].filter(label=>label!==text.games))assert.equal(html.includes(`>${label}<`),false)}else{assert.ok(html.includes('data-world-data-quiz'));assert.ok(html.includes('data-game-stats'));assert.ok(html.includes(text.gameStatsTitle));assert.ok(html.includes(text.howTitle));assert.ok(html.includes(text.how));assert.ok(html.includes(text.winRule));assert.ok(html.includes('World Bank — World Development Indicators'))}}const about=readFileSync(institutionalFileFor(INSTITUTIONAL_PAGES.about[language]),'utf8');assert.equal((about.match(/data-about-overview/g)||[]).length,1,`${language}: marcador About`);assert.ok(about.includes(`<p data-about-overview>${ABOUT_DESCRIPTION[language]}</p>`),`${language}: descripción About`);for(const other of languages.filter(code=>code!==language))assert.equal(about.includes(`<p data-about-overview>${ABOUT_DESCRIPTION[other]}</p>`),false,`${language}: descripción de ${other}`)}
assert.deepEqual(bidiSegments('2004'),[{text:'2004',isolate:true}]);assert.deepEqual(bidiSegments('2004–2024'),[{text:'2004–2024',isolate:true}]);assert.deepEqual(bidiSegments('من 2004 إلى 2024'),[{text:'من ',isolate:false},{text:'2004',isolate:true},{text:' إلى ',isolate:false},{text:'2024',isolate:true}]);
const bidiNodes=[];globalThis.document={createElement:tag=>({tag})};appendBidiText({append:(...nodes)=>bidiNodes.push(...nodes)},'من 2004 إلى 2024','ar');delete globalThis.document;assert.deepEqual(bidiNodes.map(node=>typeof node==='string'?node:{tag:node.tag,dir:node.dir,className:node.className,textContent:node.textContent}),['من ',{tag:'bdi',dir:'ltr',className:'bidi-number',textContent:'2004'},' إلى ',{tag:'bdi',dir:'ltr',className:'bidi-number',textContent:'2024'}]);
const sitemap=readFileSync(join(root,'sitemap.xml'),'utf8');for(const routes of Object.values(GAME_PAGES))for(const route of Object.values(routes))assert.equal((sitemap.match(new RegExp(`<loc>${origin}${route}</loc>`,'g'))||[]).length,1);assert.doesNotMatch(sitemap,/assets\/data\/games|world-data-quiz\/20\d\d-/);
console.log('games-i18n-static: 30 pages, 15 languages, SEO, RTL, switcher and sitemap OK');
