import assert from 'node:assert/strict';
import * as CORE from '../assets/js/data-core.mjs';
import * as CHANGE from '../assets/js/data-change-core.mjs';
import { loadGameInputs, candidatePools, generateChallenge } from '../scripts/build-world-data-quiz.mjs';
import { validateChallenge, hintEliminations } from '../assets/js/games/world-data-quiz-core.mjs';

const inputs=await loadGameInputs(),pools=candidatePools(inputs.registry,inputs.dataBySlug,inputs.countries),validCountries=new Set(inputs.countries.filter(country=>!country.is_aggregate).map(country=>country.id)),candidateTotal=[...pools.values()].reduce((sum,items)=>sum+items.length,0);assert.ok(candidateTotal>1000);
for(let offset=0;offset<120;offset++){const date=`2027-${String(Math.floor(offset/28)+1).padStart(2,'0')}-${String(offset%28+1).padStart(2,'0')}`,first=generateChallenge(date,inputs.registry,inputs.dataBySlug,inputs.countries,pools),second=generateChallenge(date,inputs.registry,inputs.dataBySlug,inputs.countries,pools);assert.deepEqual(first,second);assert.ok(validateChallenge(first));assert.equal(new Set(first.questions.map(question=>question.indicatorId)).size,5);const categoryCounts=Object.values(Object.groupBy(first.questions,question=>question.category)).map(items=>items.length);assert.ok(Math.max(...categoryCounts)<=2);for(const question of first.questions){assert.equal(new Set(question.options.map(option=>option.country)).size,4);assert.ok(question.options.every(option=>validCountries.has(option.country)&&Number.isFinite(option.value)));assert.equal(question.options.filter(option=>option.country===question.correctCountry).length,1);const item=inputs.registry.indicators.find(entry=>entry.id===question.indicatorId),values=question.options.map(option=>option.value),expected=['highest','increase'].includes(question.type)?Math.max(...values):Math.min(...values);assert.equal(question.options.find(option=>option.country===question.correctCountry).value,expected);const formatted=question.options.map(option=>question.fromYear==null?CORE.formatIndicatorValue(option.value,item,'en-US','table'):CHANGE.formatChange(option.change,item,'en-US','table'));assert.equal(new Set(formatted).size,4);assert.equal(hintEliminations(question).length,2);assert.equal(hintEliminations(question).includes(question.correctCountry),false);if(question.fromYear!=null)for(const option of question.options){assert.ok(Number.isFinite(option.from)&&Number.isFinite(option.to));assert.equal(option.change,CHANGE.calculateChange(option.from,option.to,CHANGE.changeType(item)))}}}
console.log(`games-generator: 120 challenges and ${candidateTotal} candidates validated`);

