import assert from 'node:assert/strict';
import { localDateKey, dailySeed, seededRandom } from '../assets/js/games/game-daily.mjs';
import { parseStore, defaultStore, gameState, setSession, completeGame, derivedStats } from '../assets/js/games/game-storage.mjs';
import { scoreAnswer, isWin, hintEliminations, freshSession, normalizeSession, answerQuestion, continueSession, useHint } from '../assets/js/games/world-data-quiz-core.mjs';
import { resultSquares, shareText, shareResult } from '../assets/js/games/game-share.mjs';

assert.equal(scoreAnswer(true,false),2);assert.equal(scoreAnswer(true,true),1);assert.equal(scoreAnswer(false,false),0);assert.equal(isWin(3),true);assert.equal(isWin(2),false);
assert.equal(localDateKey(new Date(2026,8,16,23,59)),'2026-09-16');assert.equal(localDateKey(new Date(2026,8,17,0,1)),'2026-09-17');assert.equal(dailySeed('worldDataQuiz','2026-09-16',1),'worldDataQuiz:v1:2026-09-16');assert.equal(seededRandom('same')(),seededRandom('same')());
assert.deepEqual(parseStore('{broken'),defaultStore());const future={schemaVersion:9,games:{worldDataQuiz:{futureField:7}},unknown:'keep'};assert.equal(gameState(parseStore(JSON.stringify(future)),'worldDataQuiz').futureField,7);
const question={id:'q1',correctCountry:'ESP',options:['ESP','FRA','DEU','ITA'].map(country=>({country}))};const challenge={date:'2026-09-16',generatorVersion:1,questions:[question,question,question,question,question]};let session=freshSession(challenge);session=useHint(session,question);assert.equal(session.hintByQuestion.q1.length,2);assert.equal(session.hintByQuestion.q1.includes('ESP'),false);assert.deepEqual(hintEliminations(question),hintEliminations(question));session=answerQuestion(session,question,'ESP');assert.equal(session.score,1);assert.equal(session.correct,1);assert.deepEqual(answerQuestion(session,question,'FRA'),session);session=continueSession(session);assert.equal(session.current,1);assert.equal(normalizeSession(session,challenge).score,1);
let store=setSession(defaultStore(),'worldDataQuiz','2026-09-14',session);store=completeGame(store,'worldDataQuiz','2026-09-14',{score:8,correct:4});store=completeGame(store,'worldDataQuiz','2026-09-14',{score:8,correct:4});assert.equal(gameState(store,'worldDataQuiz').stats.gamesPlayed,1);store=completeGame(store,'worldDataQuiz','2026-09-15',{score:10,correct:5});let stats=derivedStats(gameState(store,'worldDataQuiz').stats);assert.equal(stats.currentStreak,2);assert.equal(stats.bestStreak,2);assert.equal(stats.perfectGames,1);store=completeGame(store,'worldDataQuiz','2026-09-17',{score:2,correct:1});stats=derivedStats(gameState(store,'worldDataQuiz').stats);assert.equal(stats.currentStreak,1);assert.equal(stats.bestStreak,2);assert.equal(stats.gamesPlayed,3);assert.equal(stats.wins,2);
const isolated=completeGame(store,'futureGame','2026-09-17',{score:1,correct:1},1);assert.equal(gameState(isolated,'worldDataQuiz').stats.gamesPlayed,3);assert.equal(gameState(isolated,'futureGame').stats.gamesPlayed,1);assert.equal(gameState(isolated,'futureGame').stats.wins,1);
assert.equal(resultSquares([{correct:true,hintUsed:false},{correct:true,hintUsed:true},{correct:false}]),'🟩🟨⬛');assert.doesNotMatch(shareText({title:'Quiz',date:'Sep 16',score:8,correct:4,answers:[{correct:true,hintUsed:false}],streak:2,url:'https://example.test',labels:{streak:'days'}}),/ESP|France|answer/i);
let shared='',copied='';assert.equal(await shareResult('result',{share:async payload=>{shared=payload.text}}),'shared');assert.equal(shared,'result');assert.equal(await shareResult('fallback',{clipboard:{writeText:async value=>{copied=value}}}),'copied');assert.equal(copied,'fallback');
console.log('games-core: scoring, win, hint, resume, storage, streak, deduplication and share OK');
