import assert from 'node:assert/strict';
import {existsSync,readFileSync} from 'node:fs';
import {join,resolve} from 'node:path';
import {DATA_LANGUAGES} from '../assets/js/data-routes.mjs';
import {GAME_PAGES} from '../assets/js/games/game-routes.mjs';
import {GEO_QUIZ_I18N,GEO_QUIZ_QUESTION_TYPES,GEO_QUIZ_REQUIRED_KEYS} from '../assets/js/games/geo-quiz-i18n.mjs';
import {seededRandom} from '../assets/js/games/game-daily.mjs';
import {FAMILIES,GEO_QUIZ_VERSION,blankGeoTrainingMemory,buildGeoCandidates,compatibleGeoQuestions,dailyGeoQuestions,geoQuestionById,geoSummary,geoTrainingType,localizedEntityLabel,normalizeGeoSession,selectGeoTrainingQuestion,topologyNeighbors,validateGeoCandidates} from '../assets/js/games/geo-quiz-core.mjs';

const root=resolve(import.meta.dirname,'..'),json=path=>JSON.parse(readFileSync(join(root,path),'utf8'));
const catalog=json('assets/data/geo-quiz/catalog.json'),metadata=json('assets/data/geo-quiz/metadata.json'),countries=json('assets/data/worldbank/countries.json').countries,topology=json('assets/maps/world-50m.topo.json');
const wdi={poblacion:json('assets/data/worldbank/poblacion.json'),'esperanza-de-vida':json('assets/data/worldbank/esperanza-de-vida.json'),'pib-per-capita':json('assets/data/worldbank/pib-per-capita.json')},candidates=buildGeoCandidates({catalog,countries,topology,wdi});
assert.equal(metadata.sources.length,3);for(const source of metadata.sources)for(const key of ['source_name','source_url','license_name','license_url','retrieved_at','transformation_notes'])assert.ok(source[key]);
assert.deepEqual([catalog.cities.length,catalog.mountains.length,catalog.rivers.length,catalog.islands.length,catalog.volcanoes.length+catalog.mountains.filter(item=>item.is_volcano).length,catalog.seas.length,catalog.oceans.length],[24,8,8,8,10,9,5]);
for(const item of [...catalog.cities,...catalog.mountains,...catalog.rivers,...catalog.islands,...catalog.volcanoes,...catalog.seas,...catalog.oceans]){assert.match(item.id,/^Q\d+$/);assert.ok(item.source);if(item.coordinates)assert.ok(item.coordinates[0]>=-180&&item.coordinates[0]<=180&&item.coordinates[1]>=-90&&item.coordinates[1]<=90)}
for(const river of catalog.rivers){assert.ok(river.countries.length);assert.ok(river.validated);if(river.source_country)assert.ok(river.countries.includes(river.source_country))}
assert.equal(metadata.schema_version,2);assert.equal(GEO_QUIZ_VERSION,2);assert.deepEqual(FAMILIES,['visual','human','physical','maritime','political','data']);
assert.equal(candidates.length,613);assert.ok(validateGeoCandidates(candidates));for(const item of candidates){assert.equal(item.options.length,4);assert.equal(new Set(item.options.map(option=>option.kind+option.id)).size,4);assert.equal(item.options.filter(option=>`${option.kind}:${option.id}`===item.correct).length,1)}
const typeCounts=Object.fromEntries(Object.entries(Object.groupBy(candidates,item=>item.type)).map(([type,items])=>[type,items.length]));
assert.deepEqual(Object.fromEntries(['volcanoCountry','countryVolcano','seaCoast','seaNotCoast','countrySea','seaOcean','countryOcean','oceanCoast','oceanNotCoast'].map(type=>[type,typeCounts[type]])),{volcanoCountry:8,countryVolcano:8,seaCoast:9,seaNotCoast:9,countrySea:7,seaOcean:4,countryOcean:15,oceanCoast:4,oceanNotCoast:4});
for(const volcano of catalog.volcanoes.filter(item=>item.countries.length>1)){assert.equal(candidates.some(item=>item.central===volcano.id),false,`${volcano.id}: border volcano must not generate single-country questions`)}
for(const item of candidates.filter(item=>item.type==='countrySea')){const country=item.subjectCountry;assert.equal(item.options.filter(option=>catalog.seas.find(sea=>sea.id===option.id)?.coastal_countries.includes(country)).length,1,`${item.id}: ambiguous sea options`)}
for(const item of candidates.filter(item=>item.type==='countryOcean')){const country=item.subjectCountry;assert.equal(catalog.oceans.filter(ocean=>ocean.coastal_countries.includes(country)).length,1,`${item.id}: multi-ocean country`)}
for(const sea of catalog.seas){assert.ok(sea.coastal_countries.length);assert.equal(new Set(sea.coastal_countries).size,sea.coastal_countries.length);assert.equal(sea.regional_distractors.some(code=>sea.coastal_countries.includes(code)),false);if(sea.parent_ocean)assert.ok(['Q23406','Q1693','Q27092','Q58705'].includes(sea.id))}
assert.deepEqual(catalog.oceans.map(item=>item.code).sort(),['ARC','ATL','IND','PAC','SOU']);
assert.ok(topologyNeighbors(topology).get('DEU').includes('FRA'));assert.notEqual(localizedEntityLabel(catalog.cities[0],'zh-CN'),catalog.cities[0].labels.en);
const seenFamilies=new Set;for(const date of ['2026-01-15','2026-01-16','2026-01-17','2026-12-31','2027-01-01']){const a=dailyGeoQuestions(candidates,date);assert.deepEqual(a,dailyGeoQuestions(candidates,date));assert.equal(a.length,5);assert.equal(new Set(a).size,5);assert.equal(new Set(a.map(id=>geoQuestionById(candidates,id).family)).size,5);a.forEach(id=>seenFamilies.add(geoQuestionById(candidates,id).family))}assert.deepEqual([...seenFamilies].sort(),[...FAMILIES].sort());
const dailySnapshots={
  '2026-01-15':['wdi:pib-per-capita:7:2025','island-country:Q1460','country-ocean:GHA:ATL','country-capital:Q1770','silhouette:ZMB'],
  '2026-01-16':['island-country:Q3757','silhouette:GAB','mountain-country:Q164660','wdi:esperanza-de-vida:2:2024','country-sea:BGR:Q166'],
  '2026-12-31':['silhouette:HRV','volcano-country:Q39231','country-ocean:MOZ:IND','wdi:esperanza-de-vida:0:2024','capital-country:Q1780'],
  '2027-01-01':['country-volcano:Q524','capital-country:Q3870','silhouette:TCD','no-border:HRV','wdi:esperanza-de-vida:1:2024']
};for(const [date,ids] of Object.entries(dailySnapshots))assert.deepEqual(dailyGeoQuestions(candidates,date),ids,`${date}: daily challenge changed`);
const yearlyFamilies=Object.fromEntries(FAMILIES.map(family=>[family,0]));for(let offset=0;offset<365;offset++){const date=new Date(Date.UTC(2027,0,1+offset)).toISOString().slice(0,10);for(const id of dailyGeoQuestions(candidates,date))yearlyFamilies[geoQuestionById(candidates,id).family]++}assert.equal(Object.values(yearlyFamilies).reduce((sum,value)=>sum+value,0),1825);for(const count of Object.values(yearlyFamilies))assert.ok(count>=250&&count<=340,`daily family imbalance: ${JSON.stringify(yearlyFamilies)}`);
function trainingSequence(count,difficulty,seed){let memory=blankGeoTrainingMemory(),random=seededRandom(seed);const questions=[];for(let index=0;index<count;index++){const selected=selectGeoTrainingQuestion(candidates,difficulty,memory,random);assert.ok(selected.question,`${difficulty}: no training question`);memory=selected.memory;questions.push(selected.question)}return questions}
const training=trainingSequence(600,'all','geo-training-all'),trainingFamilies=Object.fromEntries(Object.entries(Object.groupBy(training,item=>item.family)).map(([family,items])=>[family,items.length])),trainingTypes=new Set(training.map(geoTrainingType));assert.deepEqual(Object.keys(trainingFamilies).sort(),[...FAMILIES].sort());for(const count of Object.values(trainingFamilies))assert.ok(count>=70&&count<=130,`training family imbalance: ${JSON.stringify(trainingFamilies)}`);for(const type of ['cityCountry','capitalCountry','countryCapital','mountain','river','volcano','sea','ocean','border','noBorder','islandCountry','wdiHigher','silhouette'])assert.ok(trainingTypes.has(type),`training type absent: ${type}`);
for(let index=1;index<training.length;index++){const previous=training[index-1],current=training[index],recent=training.slice(Math.max(0,index-5),index);assert.equal(recent.some(item=>item.id===current.id),false);assert.notEqual(current.family,previous.family);assert.notEqual(geoTrainingType(current),geoTrainingType(previous));assert.notEqual(current.central,previous.central);const previousCountry=previous.country||previous.subjectCountry,currentCountry=current.country||current.subjectCountry,alternatives=candidates.filter(item=>item.family===current.family&&geoTrainingType(item)===geoTrainingType(current)&&(item.country||item.subjectCountry)!==previousCountry);if(previousCountry&&currentCountry&&alternatives.length)assert.notEqual(currentCountry,previousCountry)}
for(const difficulty of ['easy','medium','hard']){const sequence=trainingSequence(300,difficulty,`geo-training-${difficulty}`),availableFamilies=new Set(candidates.filter(item=>item.difficulty===difficulty).map(item=>item.family)),usedFamilies=new Set(sequence.map(item=>item.family));assert.ok(sequence.every(item=>item.difficulty===difficulty));assert.deepEqual([...usedFamilies].sort(),[...availableFamilies].sort());for(let index=1;index<sequence.length;index++){const previous=sequence[index-1],current=sequence[index];if(availableFamilies.size>1)assert.notEqual(current.family,previous.family);assert.notEqual(current.id,previous.id);const alternatives=candidates.filter(item=>item.difficulty===difficulty&&item.family===current.family&&geoTrainingType(item)===geoTrainingType(current)&&item.central!==previous.central);if(alternatives.length)assert.notEqual(current.central,previous.central)}}
let session=normalizeGeoSession(null,'2026-01-15',dailyGeoQuestions(candidates,'2026-01-15'));session.answers[0].status='correct';session.answers[0].score=100;session.index=1;assert.equal(normalizeGeoSession(JSON.parse(JSON.stringify(session)),session.date,session.questions).index,1);assert.deepEqual(geoSummary(session),{score:100,correct:1});
const generated=dailyGeoQuestions(candidates,session.date),legacy={...session,questions:candidates.filter(item=>item.family!=='maritime').slice(0,5).map(item=>item.id)};assert.deepEqual(compatibleGeoQuestions(legacy,session.date,candidates,generated),legacy.questions);assert.deepEqual(compatibleGeoQuestions({...legacy,questions:['missing']},session.date,candidates,generated),generated);
const englishPhrases=['5 geography questions every day.','Countries, cities, rivers, mountains and more','Five mixed questions','Play daily quiz','Which country','What is the capital','Correct answer','Next question','The silhouette is'];
assert.deepEqual(Object.keys(GEO_QUIZ_I18N).sort(),Object.keys(DATA_LANGUAGES).sort());
for(const language of Object.keys(DATA_LANGUAGES)){const copy=GEO_QUIZ_I18N[language];for(const key of GEO_QUIZ_REQUIRED_KEYS){assert.ok(Object.hasOwn(copy,key),`${language}:${key}:missing`);assert.ok(typeof copy[key]==='function'||typeof copy[key]==='object'||String(copy[key]).trim(),`${language}:${key}:empty`)}if(language!=='en')for(const group of ['families','prompts','facts'])assert.notStrictEqual(copy[group],GEO_QUIZ_I18N.en[group],`${language}:${group}:fallback`);for(const type of GEO_QUIZ_QUESTION_TYPES){assert.equal(typeof copy.prompts[type],'function');assert.equal(typeof copy.facts[type],'function');assert.ok(copy.prompts[type]('ENTITY').includes('ENTITY')||type==='silhouette');assert.ok(copy.facts[type]('ENTITY','COUNTRY',2024).includes('ENTITY'))}const visible=[copy.title,copy.tagline,copy.cardMeta,copy.dailyMeta,copy.how,copy.questionProgress(2,5),copy.correctAnswer('ANSWER'),copy.scoreLine(300,500),copy.streakLine(4),copy.viewDataLine('COUNTRY'),copy.shareText({date:'2026-09-17',marks:'MARKS',score:300,total:500,url:'URL'}),...Object.values(copy.families),...GEO_QUIZ_QUESTION_TYPES.flatMap(type=>[copy.prompts[type]('ENTITY'),copy.facts[type]('ENTITY','COUNTRY',2024)])].join('\n');if(language!=='en')for(const phrase of englishPhrases)assert.equal(visible.includes(phrase),false,`${language}: English contamination: ${phrase}`);const route=GAME_PAGES.geoQuiz[language],file=join(root,...route.split('/').filter(Boolean),'index.html');assert.ok(existsSync(file));const html=readFileSync(file,'utf8');assert.ok(html.includes('data-geo-quiz'));assert.ok(html.includes(`canonical" href="https://metaphai.com${route}`));if(language==='ar')assert.ok(html.includes('<html lang="ar" dir="rtl">'));if(language!=='en')for(const phrase of englishPhrases.slice(0,5))assert.equal(html.includes(phrase),false,`${language}:html English contamination: ${phrase}`)}
const ui=readFileSync(join(root,'assets/js/games/geo-quiz-ui.mjs'),'utf8');for(const phrase of ['Play daily quiz','Correct answer','Next question','MetaphAI Geo Quiz'])assert.equal(ui.includes(phrase),false);for(const key of ['questionProgress','correctAnswer','scoreLine','streakLine','correctLine','viewDataLine','shareText'])assert.ok(ui.includes(`text.${key}`));
console.log(`geo-quiz: ${candidates.length} candidates, 68 curated volcano/sea/ocean candidates, 15 complete languages, ${GEO_QUIZ_QUESTION_TYPES.length} localized question templates, daily v2 and legacy-session compatibility OK`);
