import assert from 'node:assert/strict';
import {existsSync,readFileSync} from 'node:fs';
import {join,resolve} from 'node:path';
import {DATA_LANGUAGES} from '../assets/js/data-routes.mjs';
import {GAME_PAGES} from '../assets/js/games/game-routes.mjs';
import {GEO_QUIZ_I18N,GEO_QUIZ_QUESTION_TYPES,GEO_QUIZ_REQUIRED_KEYS} from '../assets/js/games/geo-quiz-i18n.mjs';
import {buildGeoCandidates,dailyGeoQuestions,geoQuestionById,geoSummary,localizedEntityLabel,normalizeGeoSession,topologyNeighbors,validateGeoCandidates} from '../assets/js/games/geo-quiz-core.mjs';

const root=resolve(import.meta.dirname,'..'),json=path=>JSON.parse(readFileSync(join(root,path),'utf8'));
const catalog=json('assets/data/geo-quiz/catalog.json'),metadata=json('assets/data/geo-quiz/metadata.json'),countries=json('assets/data/worldbank/countries.json').countries,topology=json('assets/maps/world-50m.topo.json');
const wdi={poblacion:json('assets/data/worldbank/poblacion.json'),'esperanza-de-vida':json('assets/data/worldbank/esperanza-de-vida.json'),'pib-per-capita':json('assets/data/worldbank/pib-per-capita.json')},candidates=buildGeoCandidates({catalog,countries,topology,wdi});
assert.equal(metadata.sources.length,3);for(const source of metadata.sources)for(const key of ['source_name','source_url','license_name','license_url','retrieved_at','transformation_notes'])assert.ok(source[key]);
assert.deepEqual([catalog.cities.length,catalog.mountains.length,catalog.rivers.length,catalog.islands.length],[24,8,8,8]);
for(const item of [...catalog.cities,...catalog.mountains,...catalog.rivers,...catalog.islands]){assert.match(item.id,/^Q\d+$/);assert.ok(item.source);if(item.coordinates)assert.ok(item.coordinates[0]>=-180&&item.coordinates[0]<=180&&item.coordinates[1]>=-90&&item.coordinates[1]<=90)}
for(const river of catalog.rivers){assert.ok(river.countries.length);assert.ok(river.validated);if(river.source_country)assert.ok(river.countries.includes(river.source_country))}
assert.equal(candidates.length,545);assert.ok(validateGeoCandidates(candidates));for(const item of candidates){assert.equal(item.options.length,4);assert.equal(new Set(item.options.map(option=>option.kind+option.id)).size,4);assert.equal(item.options.filter(option=>`${option.kind}:${option.id}`===item.correct).length,1)}
assert.ok(topologyNeighbors(topology).get('DEU').includes('FRA'));assert.notEqual(localizedEntityLabel(catalog.cities[0],'zh-CN'),catalog.cities[0].labels.en);
for(const date of ['2026-01-15','2026-12-31','2027-01-01']){const a=dailyGeoQuestions(candidates,date);assert.deepEqual(a,dailyGeoQuestions(candidates,date));assert.equal(a.length,5);assert.equal(new Set(a).size,5);assert.equal(new Set(a.map(id=>geoQuestionById(candidates,id).family)).size,5)}
let session=normalizeGeoSession(null,'2026-01-15',dailyGeoQuestions(candidates,'2026-01-15'));session.answers[0].status='correct';session.answers[0].score=100;session.index=1;assert.equal(normalizeGeoSession(JSON.parse(JSON.stringify(session)),session.date,session.questions).index,1);assert.deepEqual(geoSummary(session),{score:100,correct:1});
const englishPhrases=['5 geography questions every day.','Countries, cities, rivers, mountains and more','Five mixed questions','Play daily quiz','Which country','What is the capital','Correct answer','Next question','The silhouette is'];
assert.deepEqual(Object.keys(GEO_QUIZ_I18N).sort(),Object.keys(DATA_LANGUAGES).sort());
for(const language of Object.keys(DATA_LANGUAGES)){const copy=GEO_QUIZ_I18N[language];for(const key of GEO_QUIZ_REQUIRED_KEYS){assert.ok(Object.hasOwn(copy,key),`${language}:${key}:missing`);assert.ok(typeof copy[key]==='function'||typeof copy[key]==='object'||String(copy[key]).trim(),`${language}:${key}:empty`)}if(language!=='en')for(const group of ['families','prompts','facts'])assert.notStrictEqual(copy[group],GEO_QUIZ_I18N.en[group],`${language}:${group}:fallback`);for(const type of GEO_QUIZ_QUESTION_TYPES){assert.equal(typeof copy.prompts[type],'function');assert.equal(typeof copy.facts[type],'function');assert.ok(copy.prompts[type]('ENTITY').includes('ENTITY')||type==='silhouette');assert.ok(copy.facts[type]('ENTITY','COUNTRY',2024).includes('ENTITY'))}const visible=[copy.title,copy.tagline,copy.cardMeta,copy.dailyMeta,copy.how,copy.questionProgress(2,5),copy.correctAnswer('ANSWER'),copy.scoreLine(300,500),copy.streakLine(4),copy.viewDataLine('COUNTRY'),copy.shareText({date:'2026-09-17',marks:'MARKS',score:300,total:500,url:'URL'}),...Object.values(copy.families),...GEO_QUIZ_QUESTION_TYPES.flatMap(type=>[copy.prompts[type]('ENTITY'),copy.facts[type]('ENTITY','COUNTRY',2024)])].join('\n');if(language!=='en')for(const phrase of englishPhrases)assert.equal(visible.includes(phrase),false,`${language}: English contamination: ${phrase}`);const route=GAME_PAGES.geoQuiz[language],file=join(root,...route.split('/').filter(Boolean),'index.html');assert.ok(existsSync(file));const html=readFileSync(file,'utf8');assert.ok(html.includes('data-geo-quiz'));assert.ok(html.includes(`canonical" href="https://metaphai.com${route}`));if(language==='ar')assert.ok(html.includes('<html lang="ar" dir="rtl">'));if(language!=='en')for(const phrase of englishPhrases.slice(0,5))assert.equal(html.includes(phrase),false,`${language}:html English contamination: ${phrase}`)}
const ui=readFileSync(join(root,'assets/js/games/geo-quiz-ui.mjs'),'utf8');for(const phrase of ['Play daily quiz','Correct answer','Next question','MetaphAI Geo Quiz'])assert.equal(ui.includes(phrase),false);for(const key of ['questionProgress','correctAnswer','scoreLine','streakLine','correctLine','viewDataLine','shareText'])assert.ok(ui.includes(`text.${key}`));
console.log(`geo-quiz: ${candidates.length} candidates, 15 complete languages, 13 localized question templates, no visible English fallback, daily logic and persistence OK`);
