import assert from 'node:assert/strict';
import {existsSync,readFileSync,readdirSync,statSync} from 'node:fs';
import {join,relative,resolve} from 'node:path';
import {DATA_LANGUAGES,DATA_PAGES,INSTITUTIONAL_PAGES} from '../assets/js/data-routes.mjs';
import {GAME_PAGES} from '../assets/js/games/game-routes.mjs';
import {gameText} from '../assets/js/games/games-i18n.mjs';

const root=resolve(import.meta.dirname,'..'),languages=Object.keys(DATA_LANGUAGES);
const excluded=new Set(['worked','.git','node_modules']);
const prefixes={es:'datos-globales/',en:'en/global-data/',fr:'fr/donnees-mondiales/',de:'de/weltdaten/',it:'it/dati-globali/',pt:'pt/dados-globais/',ru:'ru/global-data/','zh-CN':'zh-cn/global-data/',hi:'hi/global-data/',ja:'ja/global-data/',ko:'ko/global-data/',ca:'ca/global-data/',ar:'ar/global-data/',id:'id/global-data/',bn:'bn/global-data/'};
const dataLabels={es:'Datos globales',en:'Global data',fr:'Données mondiales',de:'Weltdaten',it:'Dati globali',pt:'Dados globais',ru:'Мировые данные','zh-CN':'全球数据',hi:'वैश्विक डेटा',ja:'世界データ',ko:'세계 데이터',ca:'Dades globals',ar:'البيانات العالمية',id:'Data global',bn:'বৈশ্বিক তথ্য'};
prefixes.zh=prefixes['zh-CN'];dataLabels.zh=dataLabels['zh-CN'];DATA_PAGES.home.zh=DATA_PAGES.home['zh-CN'];
const hrefs=['/','/calendarios-laborales/','/datos-globales/','/juegos/'],labels=['Calculadoras','Calendarios','Datos globales','Juegos'];
function walk(dir){return readdirSync(dir).flatMap(name=>{if(excluded.has(name))return[];const path=join(dir,name),stats=statSync(path);return stats.isDirectory()?walk(path):path.endsWith('.html')&&name!=='indexv1.html'?[path]:[]})}
function links(fragment){return [...fragment.matchAll(/<a\s+([^>]*?)>([\s\S]*?)<\/a>/g)].map(match=>({attrs:match[1],text:match[2].replace(/<[^>]+>/g,'').trim(),href:match[1].match(/href="([^"]+)"/)?.[1]}))}
function localExists(href){return href==='/'||existsSync(href.endsWith('/')?join(root,href.slice(1),'index.html'):join(root,href.slice(1)))}

const pages=walk(root).map(file=>({file,rel:relative(root,file).replaceAll('\\','/'),html:readFileSync(file,'utf8')})).filter(page=>page.html.includes('<header'));
const spanish=pages.filter(page=>/<html lang="es(?:-|\")/.test(page.html)),international=pages.filter(page=>/<html lang="(en|fr|de|it|pt|ru|zh-CN|hi|ja|ko|ca|ar|id|bn)(?:-|\")/.test(page.html));
assert.ok(spanish.length>=274);assert.ok(international.length>=3528);
for(const {file,rel,html} of spanish){const header=html.match(/<header[\s\S]*?<\/header>/)[0],nav=header.match(/<nav class="site-nav"[\s\S]*?<\/nav>/)?.[0]||'',primary=nav.match(/<div class="site-nav-primary">([\s\S]*?)<\/div>/)?.[1]||'',items=links(primary);assert.deepEqual(items.map(item=>item.href),hrefs,`${rel}: destinos ES`);assert.deepEqual(items.map(item=>item.text),labels,`${rel}: labels ES`);for(const item of items)assert.ok(localExists(item.href),`${rel}: enlace roto ${item.href}`);const current=items.filter(item=>item.attrs.includes('aria-current="page"'));if(rel.startsWith('datos-globales/'))assert.deepEqual(current.map(item=>item.href),['/datos-globales/']);else if(rel.startsWith('juegos/'))assert.deepEqual(current.map(item=>item.href),['/juegos/']);else if(rel==='calendarios-laborales/index.html')assert.deepEqual(current.map(item=>item.href),['/calendarios-laborales/']);else if(/^(index\.html|calculadora-|planificador-|simulador-)/.test(rel))assert.deepEqual(current.map(item=>item.href),['/']);else assert.equal(current.length,0);assert.equal((header.match(/<nav\b/g)||[]).length,1);assert.ok(header.includes('<a href="/" class="logo">'))}
for(const {rel,html} of international){const lang=html.match(/<html lang="([^"]+)/)[1],header=html.match(/<header[\s\S]*?<\/header>/)[0],primary=header.match(/<div class="site-nav-primary">([\s\S]*?)<\/div>/)?.[1]||'',items=links(primary);assert.equal(items.length,2,`${rel}: identidades Global data + Games`);assert.deepEqual(items.map(item=>item.href),[DATA_PAGES.home[lang],GAME_PAGES.home[lang]]);assert.deepEqual(items.map(item=>item.text),[dataLabels[lang],gameText(lang).games]);for(const item of items)assert.ok(localExists(item.href));assert.equal(header.includes('href="/calendarios-laborales/"'),false);assert.ok(header.includes('data-language-switcher'));const current=items.filter(item=>item.attrs.includes('aria-current="page"'));if(rel.startsWith(prefixes[lang]))assert.deepEqual(current.map(item=>item.href),[DATA_PAGES.home[lang]]);else if(Object.values(GAME_PAGES).some(routes=>rel===routes[lang].slice(1)+'index.html'))assert.deepEqual(current.map(item=>item.href),[GAME_PAGES.home[lang]]);else assert.equal(current.length,0);assert.ok(header.includes('<a href="/" class="logo">'))}
for(const page of Object.values(INSTITUTIONAL_PAGES))for(const lang of languages)assert.ok(pages.some(item=>item.rel===(page[lang].endsWith('.html')?page[lang].slice(1):`${page[lang].slice(1)}index.html`)),`${page[lang]}: institucional no auditada`);
const logoCss=readFileSync(join(root,'assets','metaphai-logo.css'),'utf8'),dataCss=readFileSync(join(root,'assets','css','data.css'),'utf8');assert.match(logoCss,/grid-template-columns: minmax\(0, 1fr\) auto minmax\(0, 1fr\)/);assert.match(logoCss,/\.site-nav-link \{[\s\S]*?min-height: 44px/);assert.match(logoCss,/@media \(max-width: 720px\)[\s\S]*?"logo tools"[\s\S]*?"primary primary"/);assert.match(logoCss,/@media \(max-width: 390px\)[\s\S]*?\.site-nav-link \{ min-height: 40px/);assert.match(dataCss,/@media\(max-width:720px\)[\s\S]*?data-header-tools\{grid-area:tools/);
console.log(`header-navigation-static: ${spanish.length} ES y ${international.length} internacionales; rutas, activos, ARIA y responsive OK`);
