import assert from 'node:assert/strict';
import {existsSync,readFileSync,readdirSync,statSync} from 'node:fs';
import {join,relative,resolve} from 'node:path';
import {DATA_LANGUAGES,DATA_PAGES} from '../assets/js/data-routes.mjs';
import {GAME_PAGES} from '../assets/js/games/game-routes.mjs';
import {gameText} from '../assets/js/games/games-i18n.mjs';
import {GEOGRAPHY_ROUTES} from '../assets/js/geography-routes.mjs';
import {geographyText} from '../assets/js/geography-i18n.mjs';
const root=resolve(import.meta.dirname,'..'),excluded=new Set(['worked','.git','node_modules']),dataLabels={es:'Datos globales',en:'Global data',fr:'Données mondiales',de:'Weltdaten',it:'Dati globali',pt:'Dados globais',ru:'Мировые данные','zh-CN':'全球数据',hi:'वैश्विक डेटा',ja:'世界データ',ko:'세계 데이터',ca:'Dades globals',ar:'البيانات العالمية',id:'Data global',bn:'বৈশ্বিক তথ্য'};
function walk(dir){return readdirSync(dir).flatMap(name=>{if(excluded.has(name))return[];const path=join(dir,name),stats=statSync(path);return stats.isDirectory()?walk(path):path.endsWith('.html')&&name!=='indexv1.html'?[path]:[]})}
function links(fragment){return[...fragment.matchAll(/<a\s+([^>]*?)>([\s\S]*?)<\/a>/g)].map(match=>({attrs:match[1],text:match[2].replace(/<[^>]+>/g,'').trim(),href:match[1].match(/href="([^"]+)"/)?.[1]}))}
const pages=walk(root).map(file=>({rel:relative(root,file).replaceAll('\\','/'),html:readFileSync(file,'utf8')})).filter(page=>page.html.includes('class="site-nav-primary"'));
for(const {rel,html} of pages){const lang=html.match(/<html lang="([^"]+)/)?.[1]||'es';if(!DATA_LANGUAGES[lang])continue;const primary=html.match(/<div class="site-nav-primary">([\s\S]*?)<\/div>/)?.[1]||'',items=links(primary);if(lang==='es')assert.deepEqual(items.map(item=>item.href),['/calculadoras/','/calendarios-laborales/','/datos-globales/','/geografia/','/juegos/'],`${rel}: nav ES`);else{assert.deepEqual(items.map(item=>item.href),[DATA_PAGES.home[lang],GEOGRAPHY_ROUTES.home[lang],GAME_PAGES.home[lang]],`${rel}: nav internacional`);assert.deepEqual(items.map(item=>item.text),[dataLabels[lang],geographyText(lang).geography,gameText(lang).games]);assert.equal(primary.includes('/calendarios-laborales/'),false)}for(const item of items){const path=item.href.endsWith('/')?join(root,item.href.slice(1),'index.html'):join(root,item.href.slice(1));assert.ok(item.href==='/'||existsSync(path),`${rel}: ${item.href}`)}if(rel.startsWith(GEOGRAPHY_ROUTES.home[lang].slice(1)))assert.deepEqual(items.filter(item=>item.attrs.includes('aria-current')).map(item=>item.href),[GEOGRAPHY_ROUTES.home[lang]])}
const css=readFileSync(join(root,'assets/metaphai-logo.css'),'utf8');assert.match(css,/@media \(max-width: 940px\)[\s\S]*?"logo tools"[\s\S]*?"primary primary"/);assert.match(css,/@media \(max-width: 390px\)[\s\S]*?min-height: 40px/);console.log(`header-navigation-static: ${pages.length} páginas, Geografía y responsive OK`);
