import assert from 'node:assert/strict';
import {existsSync,readFileSync,readdirSync,statSync} from 'node:fs';
import {join,relative,resolve} from 'node:path';
import {DATA_LANGUAGES,DATA_PAGES,INSTITUTIONAL_PAGES} from '../assets/js/data-routes.mjs';

const root=resolve(import.meta.dirname,'..'),languages=Object.keys(DATA_LANGUAGES);
const excluded=new Set(['worked','.git','node_modules']);
const prefixes={es:'datos-globales/',en:'en/global-data/',fr:'fr/donnees-mondiales/',de:'de/weltdaten/',it:'it/dati-globali/',pt:'pt/dados-globais/',ru:'ru/global-data/','zh-CN':'zh-cn/global-data/',hi:'hi/global-data/',ja:'ja/global-data/',ko:'ko/global-data/'};
const dataLabels={es:'Datos globales',en:'Global data',fr:'Données mondiales',de:'Weltdaten',it:'Dati globali',pt:'Dados globais',ru:'Мировые данные','zh-CN':'全球数据',hi:'वैश्विक डेटा',ja:'世界データ',ko:'세계 데이터'};
prefixes.zh=prefixes['zh-CN'];dataLabels.zh=dataLabels['zh-CN'];DATA_PAGES.home.zh=DATA_PAGES.home['zh-CN'];
const hrefs=['/','/calendarios-laborales/','/datos-globales/'],labels=['Calculadoras','Calendarios','Datos globales'];
function walk(dir){return readdirSync(dir).flatMap(name=>{if(excluded.has(name))return[];const path=join(dir,name),stats=statSync(path);return stats.isDirectory()?walk(path):path.endsWith('.html')&&name!=='indexv1.html'?[path]:[]})}
function links(fragment){return [...fragment.matchAll(/<a\s+([^>]*?)>([\s\S]*?)<\/a>/g)].map(match=>({attrs:match[1],text:match[2].replace(/<[^>]+>/g,'').trim(),href:match[1].match(/href="([^"]+)"/)?.[1]}))}
function localExists(href){return href==='/'||existsSync(href.endsWith('/')?join(root,href.slice(1),'index.html'):join(root,href.slice(1)))}

const pages=walk(root).map(file=>({file,rel:relative(root,file).replaceAll('\\','/'),html:readFileSync(file,'utf8')})).filter(page=>page.html.includes('<header'));
const spanish=pages.filter(page=>/<html lang="es(?:-|\")/.test(page.html)),international=pages.filter(page=>/<html lang="(en|fr|de|it|pt|ru|zh-CN|hi|ja|ko)(?:-|\")/.test(page.html));
assert.equal(spanish.length,36);assert.equal(international.length,140);
for(const {file,rel,html} of spanish){const header=html.match(/<header[\s\S]*?<\/header>/)[0],nav=header.match(/<nav class="site-nav"[\s\S]*?<\/nav>/)?.[0]||'',primary=nav.match(/<div class="site-nav-primary">([\s\S]*?)<\/div>/)?.[1]||'',items=links(primary);assert.match(nav,/aria-label="Navegación principal"/);assert.deepEqual(items.map(item=>item.href),hrefs,`${rel}: destinos ES`);assert.deepEqual(items.map(item=>item.text),labels,`${rel}: labels ES`);for(const item of items)assert.ok(localExists(item.href),`${rel}: enlace roto ${item.href}`);const current=items.filter(item=>item.attrs.includes('aria-current="page"'));if(rel.startsWith('datos-globales/'))assert.deepEqual(current.map(item=>item.href),['/datos-globales/'],`${rel}: activo Datos`);else if(rel==='calendarios-laborales/index.html')assert.deepEqual(current.map(item=>item.href),['/calendarios-laborales/'],`${rel}: activo Calendarios`);else if(/^(index\.html|calculadora-|planificador-|simulador-)/.test(rel))assert.deepEqual(current.map(item=>item.href),['/'],`${rel}: activo Calculadoras`);else assert.equal(current.length,0,`${rel}: activo indebido`);assert.equal(header.includes('Ver calendarios 2026-2027'),false,`${rel}: CTA antiguo en nav`);assert.equal(header.includes('Todas las calculadoras'),false,`${rel}: enlace redundante`);assert.equal((header.match(/<nav\b/g)||[]).length,1);assert.ok(header.includes('<a href="/" class="logo">'))}
for(const {rel,html} of international){const lang=html.match(/<html lang="([^"]+)/)[1].split('-')[0],header=html.match(/<header[\s\S]*?<\/header>/)[0],primary=header.match(/<div class="site-nav-primary">([\s\S]*?)<\/div>/)?.[1]||'',items=links(primary);assert.equal(items.length,1,`${rel}: debe haber una sola identidad principal`);assert.equal(items[0].href,DATA_PAGES.home[lang]);assert.equal(items[0].text,dataLabels[lang]);assert.ok(localExists(items[0].href));assert.equal(header.includes('href="/calendarios-laborales/"'),false,`${rel}: calendario español en header`);assert.equal(header.includes('class="site-nav-link">Tools</a>'),false);assert.equal(header.includes('class="site-nav-link">Calendars</a>'),false);assert.ok(header.includes('data-language-switcher'),`${rel}: selector ausente`);if(rel.startsWith(prefixes[lang]))assert.ok(items[0].attrs.includes('aria-current="page"'),`${rel}: identidad Datos no activa`);else assert.equal(items[0].attrs.includes('aria-current'),false,`${rel}: Datos no debe estar activa en institucional`);assert.ok(header.includes('<a href="/" class="logo">'))}
for(const page of Object.values(INSTITUTIONAL_PAGES))for(const lang of languages)assert.ok(pages.some(item=>item.rel===(page[lang].endsWith('.html')?page[lang].slice(1):`${page[lang].slice(1)}index.html`)),`${page[lang]}: institucional no auditada`);
const logoCss=readFileSync(join(root,'assets','metaphai-logo.css'),'utf8'),dataCss=readFileSync(join(root,'assets','css','data.css'),'utf8');assert.match(logoCss,/grid-template-columns: minmax\(0, 1fr\) auto minmax\(0, 1fr\)/);assert.match(logoCss,/\.site-nav-link \{[\s\S]*?min-height: 44px/);assert.match(logoCss,/@media \(max-width: 720px\)[\s\S]*?"logo tools"[\s\S]*?"primary primary"/);assert.match(logoCss,/@media \(max-width: 390px\)[\s\S]*?\.site-nav-link \{ min-height: 40px/);assert.match(dataCss,/@media\(max-width:720px\)[\s\S]*?data-header-tools\{grid-area:tools/);
console.log(`header-navigation-static: ${spanish.length} ES y ${international.length} internacionales; rutas, activos, ARIA y responsive OK`);
